version: '3'
services:
  my-scripts:
    build: .
    container_name: radioToSpotify
    volumes:
      - ./cfg:/app/cfg
      - ./workfiles:/app/workfiles
    environment:
      - CFG_PATH=/app/cfg
      - refreshTokenCFG=${refreshTokenCFG}
      - base64ClientIDSecret=${base64ClientIDSecret}
      - CODE=${CODE}
    restart: unless-stopped