version: '3'
services:
  my-scripts:
    build: .
    container_name: radioToSpotify
    volumes:
      - ./cfg:/app/cfg
      - ./workfiles:/app/workfiles
    environment:
      - CFG_PATH=/app/cfg
      - CLIENT_SECRET=${CLIENT_SECRET}
      - PASSWORD=${PASSWORD}
    restart: unless-stopped