version: '3'
services:
  my-scripts:
    build: .
    container_name: radioToSpotify
    volumes:
      - ./cfg:/app/cfg
      - ./workfiles:/app/workfiles
    environment:
      - CFG_PATH=/app/cfg
      - refreshTokenCFG=${refreshTokenCFG}
      - base64ClientIDSecret=${base64ClientIDSecret}
      - CODE=${CODE}
      - LIVELLODEBUG=1
      - CRON=59 23 * * * ##esegue lo script alle 23.59 ogni giorno
    restart: unless-stopped